# Generated by Django 3.1 on 2022-04-12 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20220412_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Click to read above posts...', max_length=250, verbose_name='Snippet'),
        ),
    ]
