# Generated by Django 3.1 on 2022-04-20 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_header_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='header_image',
            new_name='header',
        ),
    ]
